# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: diffaaable
author: Jan David Fischbach

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache
  timeout: -1
  allow_errors: false
  # execute_notebooks: force
  # execute_notebooks: "off"

latex:
  latex_engine: pdflatex # one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex'
  use_jupyterbook_latex: true # use sphinx-jupyterbook-latex for pdf builds as default

# Add a bibtex file so that we can create citations

html:
  home_page_in_navbar: true
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://github.com/jan-david-fischbach/diffaaable

# Information about where the book exists on the web
repository:
  url: https://github.com/jan-david-fischbach/diffaaable
  path_to_book: docs # Optional path to your book, relative to the repository root
  branch: main # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  notebook_interface: jupyterlab
  colab_url: "https://colab.research.google.com"

sphinx:
  extra_extensions:
    - "sphinx.ext.autodoc"
    #- "sphinx.ext.autodoc.typehints"
    - "sphinx.ext.autosummary"
    - "sphinx.ext.napoleon"
    - "sphinx.ext.mathjax"
    - "sphinx_math_dollar"
    - "sphinx.ext.viewcode"
    - "matplotlib.sphinxext.plot_directive"
  config:
    nb_execution_show_tb: True
    nb_execution_raise_on_error: True
    nb_custom_formats:
        .py:
            - jupytext.reads
            - fmt: py

parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    # - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist
  myst_url_schemes: [mailto, http, https] # URI schemes that will be recognised as external URLs in Markdown links
  myst_dmath_double_inline: true  # Allow display math ($$) within an inline context
